name: Schedule Deepnote Run

on:
  schedule:
    - cron: '30 1 * * *'  # This schedules the run at 1:30 AM UTC daily

jobs:
  run-deepnote:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deepnote Notebook
        env:
          DEEPNOTE_API_TOKEN: ${{ secrets.DEEPNOTE_API_TOKEN }}
          PROJECT_ID: eb85ba0c-8f04-478c-a7e1-467751486180
          NOTEBOOK_ID: effe850319fe4a57b5ca06668bf5592c
        run: |
          curl -X POST "https://api.deepnote.com/v1/projects/$PROJECT_ID/notebooks/$NOTEBOOK_ID/execute" \
          -H "Authorization: Bearer $DEEPNOTE_API_TOKEN" \
          -H "Content-Type: application/json"
